hotfix: 버그 및 주석 제거
bitbit-Merry-go-round/Transcendence-FE pull request #110
Opened 2024-04-15 15:19 UTC by jeongyunnim

## 📌 연관된 이슈
- 없음

## 📝 작업 내용
- refresh token 기능 활성화
- httpRequest() queue 형식으로 전환
- 로그아웃 기능 활성화

## 🌳 작업 브랜치명
- `hotfix/remove-debug-message`

## 💬 리뷰 요구사항 
- 커밋별로 확인해보시고 이상한 점이 있다면 댓글 달아주시고 해당 부분 코멘트 달아주세요.
- 테스트는 내일 부탁드립니다.

2024-04-15 15:32 UTC, bartshin approved these changes

2024-04-15 18:30 UTC, bartshin requested changes
queue 코드 수정했습니다
```javascript

export function showLogoutModal() {
  const logoutModal = document.createElement('div');
  console.log('logout modal', logoutModal)
  logoutModal.innerHTML =`	
  <div id="logout-modal" class="logout-modal modal">
    <div id="logout-modal-content" class="logout-modal-content modal-content">
      <p>로그아웃 되었습니다.</p>
      <a href="/login" class="btn btn-primary">확인</a>
    </div>
  </div>
    `;
  logoutModal.querySelector('#logout-modal').style.display = 'flex';
  document.body.appendChild(logoutModal);
}

function fetch_failed(url, res) {
  showLogoutModal();
}

class CallQueue {

  /** @type {{
   *  [key in number]: {
   *    method: string,
   *    url: URL | string,
   *    body: Object,
   *    success: any,
   *    fail: any,
   *    done: boolean
   *    maxTry: number
   *   }
   *   }}
   * */
  serverCallQueue = {};
  lastId = 0;
  refreshing = false;
  running = false;

  addQueue({method, url, body, success, fail}) {
    const id = ++this.lastId;

    this.serverCallQueue[id] = ({
      method, url, body, success, fail,
      done: false, maxTry: 2,
    });
    if (!this.running) {
      this.running = true;
      this.clearQueue();
    }
    return id;
  }

  async clearQueue() {
    const ids = Object.keys(this.serverCallQueue);
    for (const id of ids) {
      if (this.refreshing) {
        setTimeout(() => {
          this.clearQueue();
        }, 500);
        return ;
      }
      const call = this.serverCallQueue[Number(id)];
      if (call.done || call.maxTry == 0)
        continue;
      await this.tryCall(call);
      if (call.done) {
        delete this.serverCallQueue[id];
      }
    }

    if (Object.keys(this.serverCallQueue).filter(id => !this.serverCallQueue[Number(id)].done).length == 0) {
      this.running = false;
    }
  }

  async tryCall(queuedCall) {
    try {
      const res = await this.getResult(queuedCall);
      queuedCall.done = true;
      if (res.status === 204) {
        queuedCall.success(res);
      } else if (res.status === 401) {
        if (queuedCall.maxTry > 0) {
          if (queuedCall.maxTry == 0)
            queuedCall.done = true;
          else {
            queuedCall.done = false;
            queuedCall.maxTry--;
          }
        }
        else {
          showLogoutModal();
          queuedCall.fail(queuedCall.url);
        }
      } else if (400 <= res.status && res.status < 600) {
        queuedCall.fail(queuedCall.url);
      } else {
        queuedCall.success(res);
      }
    }
    catch (error) {
      queuedCall.fail(queuedCall.url);
    }
  }

  async getResult(call) {
    const { method, url, body } = call;
    const refresh = localStorage.getItem("refresh")

    const headers = this.getHeader();
    const res = await fetch(url, {
      method: method,
      mode: "cors",
      headers: headers,
      body: body
    });

    if (res.status === 204) {
      return (res);
    }
    else if (res.ok) {
      return res.json();
    }
    else if (res.status === 401 && refresh) {
      this.refreshing = true;
      const refreshed = await requestRefresh();
      if (!refreshed) {
        showLogoutModal();
        return (res);
      }
      this.refreshing = false;
      return (res);
    }
    else if (res.status == 404) {
      call.done = true;
      return (res);
    }
    return res.status;
  }

  getHeader() {
    const access = localStorage.getItem("access");
    if (!access || access == "undefined") {
      return ({
        "Content-Type": "application/json"
      })
    }
    return {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${access}`
    }
  }

}

export const queue = new CallQueue();

export async function requestRefresh()
{
  const GET_TOKEN_URI = `${window.location.protocol}//${window.location.host}/api/token/refresh/`;
  const bodyOnlyRefresh = JSON.stringify({
    'refresh': `${window.localStorage.getItem('refresh')}`
  });
  try {
    const res = await fetch(GET_TOKEN_URI, {
      method: "POST",
      headers: this.getHeader(),
      body: bodyOnlyRefresh
    })
    if (!res.ok)
      return false;
    const result = await res.json();
    localStorage.setItem("access", result.access)
    localStorage.setItem("refresh", result.refresh)
    return true;
  }
  catch(error) {
    //  console.error('refresh error', error)
    return (false);
  };

}

/**
 * httpRequest.
 * @param {string} method
 * @param {string} url
 * @param {object} body
 * @param {function} success
 * @param {function} fail
 */
export default function httpRequest(method, url, body, success, fail = fetch_failed) {
  queue.addQueue({method, url, body, success, fail});
}
```

2024-04-18 08:12 UTC, hyemch approved these changes
확인 했습니다! 고생하셨습니다 😊😊

2024-04-18 08:54 UTC, eko147 approved these changes
고생하셨어요!

2024-04-18 08:57 UTC, merged