Feat/game play
bitbit-Merry-go-round/Transcendence-FE pull request #81
Opened 2024-04-10 13:57 UTC by bartshin

## 📌 연관된 이슈
https://github.com/bitbit-Merry-go-round/Transcendence-FE/issues/15

## 📝 작업 내용
게임 설정 기능

## 🌳 작업 브랜치명
https://github.com/bitbit-Merry-go-round/Transcendence-FE/tree/feat/game-play

## 💬 리뷰 요구사항 (선택)
tournament_view.js 와 match_view.js 에 코드 추가했습니다

2024-04-10 15:52 UTC, jeongyunnim requested changes
<img width="821" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/d280863d-1cea-4f64-aafe-53e9be8d50c4">

game-play 브랜치의 해당 커밋에서 테스트를 진행해보았는데, 이전과 같은 문제가 계속 발생하고 있습니다...

2024-04-10 15:52 UTC, jeongyunnim commented on front/srcs/views/config.js
로그인 허용을 위해 이 부분 처리를 해주신 것 같습니다.

2024-04-10 17:46 UTC, bartshin commented on front/srcs/views/config.js
저는 어떻게 로그인 확인을 할 지 잘 모르겠네요 따로 그부분을 뺐습니다
login_view.js 에서 처리해주세요
true를 반환하면 아무 페이지도 나오지 않으니 처리후 이동시켜 주세요
<img width="728" alt="Screen Shot 2024-04-11 at 2 43 40 AM" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/65215523/68c821c4-3cdb-44ce-8a1c-3b591cbc0680">

2024-04-11 03:49 UTC, jeongyunnim commented
<img width="1680" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/6a6bdc6f-4412-4ae5-95e6-e43bb28aa4e9">

페이지가 로드되지 않아 로그인 로직을 진행하지 못하는 오류가 발생합니다.

2024-04-11 04:35 UTC, bartshin commented
페이지 로드 전에 호출되는 함수였는데 그 안에서 처리가 어려우시면 제가 처리할게요

2024-04-11 05:52 UTC, bartshin commented
> 페이지가 로드되지 않아 로그인 로직을 진행하지 못하는 오류가 발생합니다. 오늘 출근하시면 같이 해결해봤으면 하는데요. 클러 도착하시면 연락 주세요!

처리했습니다

2024-04-11 06:50 UTC, jeongyunnim commented
로그인 정상진행 되는 것 확인했습니다!

2024-04-11 06:52 UTC, jeongyunnim reviewed
확인 완료 했습니다. 고생하셨어요!

2024-04-11 06:54 UTC, jeongyunnim approved these changes

2024-04-11 06:54 UTC, merged